language: python
python: 3.7
dist: xenial
sudo: true

services:
  - redis-server

before_install:
  - cp .env.sample .env
  - python -m pip install -U pipenv black
  - pipenv install --dev

script:
  - pytest
  - black . --check

after_success:
  - codecov
